name: capella-ros
services:
  lidar:
    image: registry.cn-hangzhou.aliyuncs.com/ritju/carto3-lidar-driver:latest
    ports:
      - 3001:3001/udp
    environment:
      - LIDAR_IP_ADDRESS=192.168.2.86
      - LIDAR_ROS_FRAME_ID=vanjee_lidar_link
    restart: unless-stopped
    network_mode: bridge
    labels:
      - "com.ritju.capella.auto-update=true"

  localizer:
    image: registry.cn-hangzhou.aliyuncs.com/ritju/carto3-localizer:latest
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri:ro
      - agent_data:/data
    environment:
      - DISPLAY=$DISPLAY
      - CARTO3_HEADLESS=true
      - CARTO3_IMU_FRAME_ID=vanjee_imu_link
      - CARTO3_LIDAR_FRAME_ID=vanjee_lidar_link
      - CARTO3_BASE_FRAME_ID=base_footprint
      - CARTO3_TF_ENFORCE_Z_PLANE=true
      - CARTO3_USE_WHEEL_ODOMETRY=true
      - CARTO3_WHEEL_RADIUS=0.15
      - CARTO3_WHEEL_ODOMETRY_TIME_OFFSET=0.0
      - CARTO3_PUBLISH_ODOM_TO_BASE=false
    runtime: nvidia
    restart: unless-stopped
    network_mode: host
    pid: host
    labels:
      - "com.ritju.capella.auto-update=true"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  core:
    image: registry.cn-hangzhou.aliyuncs.com/ritju/capella-ros-cpu-core:S1_1.0.0
    devices:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      # ****** 每台必填参数 ******
      - DISPLAY=$DISPLAY
      - CAPELLA_ROS_HEADLESS=True
      - LASER_SCAN= # 2D激光雷达型号，室内清扫机器人均为 laser_scan_wr_25， 广告机器人均为 laser_scan_wr_20，消毒机器人为 laser_scan_wj_20
      - ROBOT_VERSION=mk15 # 机器人版本，室内清扫机器人版本为 cleaner_1/2/3/4/...; 户外清扫机器人为 outdoor_cleaner_1/2/3/...; 广告机器人为 ad_1/ad_2/ad_3/ad_4_ad/ad_4_exhibition; 消毒机器人为 bainan_1/2       
      - ROBOT_LOCALIZER_MODE=3D # 定位方式 2D/3D
      - ROBOT_LOCALIZER_LIDAR=VANJEE_NEW_S1 # 定位使用的激光雷达型号 WR/LIVOX/VANJEE
      - DABAI_DCW_NUMBER=0 # 启用的奥比中光 DABAI_DCW相机数量，室内机器人 3 个，户外 4个
      - USE_AURORA_CAMERA=False # 是否使用光鉴深度相机 True/False
      - USE_LASER_LINE=False # 是否开启贴边功能
      - MULTI_ROBOT_MODE=False # 是否开启多机模式，True/False
      - MAX_LINEAR_VEL=0.5
      - SERIAL_DEVICES=ttyACM0 ttyUSB0 ttyUSB1
      - OUTDOOR_ROBOT_VERSION=outdoor_cleaner_2
        # 里程计标定参数
      - LINEAR_SCALE=0.98527
      - ANGLE_SCALE=1.108197
        # 自动回充参数
      - marker_id_and_bluetooth_mac=0:1/94:C9:60:43:BE:12,1:2/94:C9:60:43:BE:12 # 每台都需要配置

      # ****** 启用相关功能必填参数 ******
        # 开启多机模式必填参数
      - ROBOT_PRIORITY=1 # 设置机器人优先级
      - CAPELLA_ROS_NAMESPACE=REAL_ROBOT_MK10 # 设置机器人名称
      - COLLISION_RADIUS_CHECK_THRESHOLD=10 # 设置机器人路线碰撞检查阈值
      - GLOBAL_POSE_FILTER_THRESHOLD=2.8 # 设置机器人位姿碰撞检查阈值
        # 机制人2D激光雷达参数
      - LASER_MIN_ANGLE=-1.57
      - LASER_MAX_ANGLE=1.57
      - LASER_MIN_RANGE=0.05
      - LASER_MAX_RANGE=30.0
      - WR_LIDAR_IP=192.168.0.10
        # 奥比中光深度相机序列号
      - CAMERA1_NUMBER=CH22643002T
      - CAMERA2_NUMBER=CH22643009V
      - CAMERA3_NUMBER=CH2R73100JN
        # aurora 深度相机 usb_port_number
      - LEFT_AURORA_USB_PORT_NUMBER=1-1.4.2
      - RIGHT_AURORA_USB_PORT_NUMBER=1-1.4.1
      - BACK_AURORA_USB_PORT_NUMBER=1-1.4.3
      
        # gemini 335
      - FRONT_DEPTH_CAMERA_SERIAL_PORT=2-2
      - RIGHT_DEPTH_CAMERA_SERIAL_PORT=2-4.4.4.1
      - BACK_DEPTH_CAMERA_SERIAL_PORT=2-4.4.4.2
      - LEFT_DEPTH_CAMERA_SERIAL_PORT=2-4.4.4.3


      # ****** 默认参数 ******
        # CYCLONEDDS_URI参数
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=/map/dds.xml
        # Cartographer定位参数
      - LOCALIZATION_CHECK_WIDTH=10
      - LOCALIZATION_CHECK_HEIGHT=10
      - GLOBAL_LINEAR_SEARCH_WINDOW=600
      - MIN_LOCALIZATION_SCORE_FOR_OPTIMIZE=0.7
        # 自动回充参数
      - CHARGER_MARKER_TYPE=APRILTAG_DOUBLE
      - MARKER_FRAME_TRANSLATION=-0.04
      - SIMILARITY_THRESHOLD=0.99
      - MARKER_FRAME_RADIUS_THRESHOLD=0.017
      - APRILTAG_SIZE=0.04
      - BASE_LINK_DUMMY_TRANSFORM_X=-0.46
      - BASE_LINK_DUMMY_TRANSFORM_Y=0.0
      - CHARGER_CONTACT_CONDITION_TYPE=BLUETOOTH_ONLY
      - LAST_DOCKED_DISTANCE_OFFSET=0.23
      - CAMERA_BASELINK_DIS=0.024
      - APRILTAG_SINGLE_SIZE=0.237
      - CAMERAS=[{"name":"rgb_camera_front", "config_file":"front.yaml"},{"name":"rgb_camera_right", "config_file":"right.yaml"}, {"name":"rgb_camera_back", "config_file":"back.yaml"},{"name":"rgb_camera_left", "config_file":"left.yaml"}]
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /dev/dri:/dev/dri
      - /home/tj2022/map:/map
      - /dev/bus/usb:/dev/bus/usb
      - agent_data:/data
      - posegraph_export:/tmp/.posegraph_export
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/front_rplidar:/dev/front_rplidar
      - /dev/back_rplidar:/dev/back_rplidar
      - /dev/video*:/dev/video*
    platform: "linux/x86-64"
    restart: always
    privileged: true
    network_mode: host
    user: "root"
    labels:
      - "com.ritju.capella.auto-update=true"

  agent:
    image: registry.cn-hangzhou.aliyuncs.com/ritju/capella-agent:staging
    ports:
      - 6533:6533
    volumes:
      - agent_data:/data
      - posegraph_export:/tmp/.posegraph_export
      - /var/run/docker.sock:/var/run/docker.sock
      - /bin/systemctl:/bin/systemctl
      - /run/systemd/system:/run/systemd/system
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /dev/input:/dev/input
      - /run/udev/control:/run/udev/control
      - /var/run/dbus:/var/run/dbus
      - /var/run/user/1000:/tmp/var/run
      - /home/tj2022/.config/pulse:/tmp/pulse
      - agent_geologs:/tmp/CapellaAgent
    environment:
      - CAPELLA_RMS_SERVER_URL=https://edge2.comlife.com.cn
      #- CAPELLA_RMS_SERVER_URL=http://tongji.noelex.net:20080
      - CAPELLA_UPDATE_CHECK_INTERVAL=3600
      - CAPELLA_DEVICE_PROFILE=S1
      - PRODUCT_ID=N43X0SV8GT #MK15
      - CAPELLA_DEFAULT_NAVIGATION_TOLERANCE=1.5
      - CAPELLA_HBR_PACKAGE_SPEC=panel:singularity,core:capella-ros,agent:capella-agent
      - CAPELLA_ROS_LOCALIZER_NODE=non-lifecycle:/glim_ros
        #- CAPELLA_ROS_LOCALIZER_NODE=non-lifecycle:/cartographer_node
      - CAPELLA_NAVIGATION_UNDOCK_POLICY=Required
      - CAPELLA_LOW_BATTERY_WARNING_THRESHOLD=0.11
      - CAPELLA_CHG_DOCKING_TIMEOUT=300
      - CAPELLA_CHG_DOCKING_RADIUS=1.0
      - PULSE_SERVER=unix:/tmp/var/run/pulse/native
      - PULSE_COOKIE=/tmp/pulse/cookie
      - CAPELLA_KEEPOUT_ZONE_FILL=true
      # - ROS_LOCALHOST_ONLY=1
    restart: always
    privileged: true
    network_mode: host
    labels:
      - "com.ritju.capella.auto-update=true"

  panel:
    image: registry.cn-hangzhou.aliyuncs.com/ritju/mercury-panel:staging
    volumes:
      - agent_data:/agent_data
      - mercury_data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
      - /run/user/1000:/run/user/1000
      - /var/run/user/1000:/tmp/run
      - /dev/dri:/dev/dri
      # - ~/panel:/capella
    environment:
      - DISPLAY=$DISPLAY
      - MERCURY_SERVER_CHANNEL_HOST=edge2.comlife.com.cn
      - MERCURY_SERVER_CHANNEL_PORT=443
      - MERCURY_SERVER_CHANNEL_USE_SSL=true
      - MERCURY_DATA_DIR=/data
      - MERCURY_AGENT_DATA_DIR=/agent_data/player/content
      - MERCURY_AGENT_CHANNEL_HOST=host.docker.internal
      - PULSE_SERVER=unix:/tmp/run/pulse/native
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,video,display,compute
    runtime: nvidia
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "com.ritju.capella.auto-update=true"

  deep_learning:
    image: registry.cn-hangzhou.aliyuncs.com/ritju/capella-gpu-program:S1_1.0.0
    devices:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,graphics,utility
      - CAPELLA_ROS_HEADLESS=True
      - USE_AD_VIEWER_COUNT=False
      - ENABLE_TRACKING_FRONT=False
      - FRONT_DEPTH_CAMERA=0
      - PANEL_FRONT_CAMERA_FLIP=1 # 跟随摄像头翻转环境变量，0表示不翻转，1表示上下翻转，2表示左右翻转，-1表示上下左右同时翻转
      - PANEL_FRONT_CAMERA_ROTATION=0 # 跟随摄像头旋转环境变量，0表示不旋转，1表示顺时针旋转90度，2表示逆时针旋转90度，3表示旋转180度
      - PANEL_BACK_CAMERA=1
      - XDG_RUNTIME_DIR=/tmp/run
      - ROBOT_VERSION=cleaner
      - OUTDOOR_ROBOT_VERSION=outdoor_cleaner_2
      - CAMERAS=[{"name":"rgb_camera_front", "config_file":"front.yaml"},{"name":"rgb_camera_right", "config_file":"right.yaml"}, {"name":"rgb_camera_back", "config_file":"back.yaml"},{"name":"rgb_camera_left", "config_file":"left.yaml"}]
      - ENABLE_INSPECTION=False
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /dev/dri:/dev/dri
      - /home/tj2022/map:/map
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/user/1000:/tmp/run
      - /dev/bus/usb:/dev/bus/usb
    platform: "linux/x86-64"
    runtime: nvidia
    restart: unless-stopped
    network_mode: host
    privileged: true
    user: root
    labels:
      - "com.ritju.capella.auto-update=true"

  pyfun:
    image: registry.cn-hangzhou.aliyuncs.com/ritju/ros2-pyfun:latest
    environment:
      - ROBOT_ID=34
      # - RTMP_SERVER_ADDRESS=rtmp://chlrosPOKEd3tOy4brAm.tongji.cq.cn:14935/live/
      - RTMP_SERVER_ADDRESS=rtmp://chlrosPOKEd3tOy4brAm.tongji.cq.cn:15935/live/
      - VIDEO_SAVE_DAYS=0.04
      - RTMP_VIDEO_SECRET=bainankeji
      - TOPIC_CAMERA_FRONT=rgb_camera_front/image_raw
      - TOPIC_CAMERA_BACK=rgb_camera_back/image_raw
      - TOPIC_CAMERA_LEFT=rgb_camera_left/image_raw
      - TOPIC_CAMERA_RIGHT=rgb_camera_right/image_raw
      - TZ=Asia/Shanghai
    volumes:
      - video_data:/data
    restart: unless-stopped
    network_mode: host
    privileged: true
    user: root

volumes:
  agent_data:
  agent_geologs:
  posegraph_export:
  mercury_data:
  video_data:
